# Generated by Django 4.2.7 on 2025-05-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='departmental_due_receipt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nacos_due_receipt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_fee_receipt',
        ),
        migrations.RemoveField(
            model_name='student',
            name='waec_result',
        ),
    ]
