# Generated by Django 4.2.7 on 2025-05-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_remove_student_departmental_due_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.student'),
        ),
    ]
