# Generated by Django 4.2.7 on 2025-05-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_alter_document_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Hod_approved',
            new_name='hod_approved',
        ),
    ]
