# Generated by Django 4.2.7 on 2025-05-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_rename_hod_approved_document_hod_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='profile_signature/'),
        ),
    ]
