# Generated by Django 4.2.7 on 2025-06-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0012_remove_hod_signing_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.department'),
        ),
    ]
