# Generated by Django 4.2.7 on 2025-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0013_hod_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='library_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sport_director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sug_approved',
            field=models.BooleanField(default=False),
        ),
    ]
