# Generated by Django 4.2.7 on 2025-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0024_exam_and_record_image_exam_and_record_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
