# Generated by Django 4.2.7 on 2025-07-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0025_doctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.doctitle'),
        ),
    ]
