# Generated by Django 6.0.6 on 2026-07-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0026_alter_document_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sug",
            options={
                "verbose_name": "Entrepreneurship",
                "verbose_name_plural": "Entrepreneurship",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("sug", "Entrepreneurship"),
                    ("sport_director", "Sport Director"),
                    ("exams_records", "Exams and Records"),
                    ("hostel", "Hostel"),
                    ("library", "Library"),
                    ("student_affair", "Student Affairs"),
                    ("hod", "HOD"),
                ],
                default="student",
                help_text="User's position in the institution",
                max_length=20,
            ),
        ),
    ]
