# Generated by Django 4.2.13 on 2026-07-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0027_alter_customuser_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sug",
            options={
                "verbose_name": "Entrepreneurship",
                "verbose_name_plural": "Entrepreneurship",
            },
        ),
    ]
