# Generated by Django 4.2.13 on 2026-09-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0028_alter_sug_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
