# Generated by Django 4.2.13 on 2026-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0029_customuser_expo_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_of_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="first_hostel_room_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_hostel_room_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
