# Generated by Django 6.0.6 on 2026-09-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0027_alter_sug_options_alter_customuser_position"),
        ("user_accounts", "0030_student_date_of_completion_and_more"),
    ]

    operations = []
